<?php

return [
    'api_key' => env('ARTISAN_API_KEY', 'YOUR KEY'),
    'allowed_command' => [
        'list',
        'help',
        'make:controller',
        'make:model',
        'make:migration',
        'migrate',
        'migrate:rollback',
        'migrate:status',
        'db:seed',
        'cache:clear',
        'config:cache',
        'config:clear',
        'route:cache',
        'route:clear',
        'view:cache',
        'view:clear',
        'queue:work',
        'queue:restart',
        'queue:listen',
        'queue:retry',
        'queue:failed',
        'queue:flush',
        'queue:failed-table',
        'storage:link',
        'event:generate',
        'event:cache',
        'event:clear',
        'event:failed',
        'event:listen',
        'schedule:run',
        'schedule:finish',
        'schedule:clear-cache',
        'schedule:list',
        'optimize',
        'optimize:clear',
        'serve',
        'tinker',
        'test',
    ],
];
